//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApp.SlowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SlowService.ISlowService")]
    public interface ISlowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlowService/Delay", ReplyAction="http://tempuri.org/ISlowService/DelayResponse")]
        string Delay(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlowService/Delay", ReplyAction="http://tempuri.org/ISlowService/DelayResponse")]
        System.Threading.Tasks.Task<string> DelayAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISlowServiceChannel : MvcWebApp.SlowService.ISlowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SlowServiceClient : System.ServiceModel.ClientBase<MvcWebApp.SlowService.ISlowService>, MvcWebApp.SlowService.ISlowService {
        
        public SlowServiceClient() {
        }
        
        public SlowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SlowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SlowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Delay(int value) {
            return base.Channel.Delay(value);
        }
        
        public System.Threading.Tasks.Task<string> DelayAsync(int value) {
            return base.Channel.DelayAsync(value);
        }
    }
}
